src/main/java/com/tucklets/app/containers/ChildAndSponsor.java, src/main/java/com/tucklets/app/controllers/SponsorInfoController.java, src/main/java/com/tucklets/app/db/repositories/ChildAndSponsorAssociationRepository.java, src/main/java/com/tucklets/app/entities/ChildAndSponsorAssoc.java, src/main/java/com/tucklets/app/entities/Sponsor.java, src/main/java/com/tucklets/app/services/ChildAndSponsorAssociationService.java, src/main/java/com/tucklets/app/services/ChildService.java, src/main/resources/static/css/sponsor-info.css, src/main/resources/templates/sponsor-info.html
Saving values to db on sponsor submit
added the selected children on sponsor info page
added container object: ChildAndSponsor
minor UI updates
=> connection to association table

build.gradle, src/main/java/com/tucklets/app/configs/SpringWebSecurityConfig.java, src/main/java/com/tucklets/app/controllers/AdminController.java, src/main/java/com/tucklets/app/controllers/BasicController.java, src/main/java/com/tucklets/app/controllers/GeneralErrorController.java, src/main/java/com/tucklets/app/controllers/LoginController.java, src/main/java/com/tucklets/app/controllers/SponsorInfoController.java, src/main/java/com/tucklets/app/db/repositories/AdminRepository.java, src/main/java/com/tucklets/app/db/repositories/ChildRepository.java, src/main/java/com/tucklets/app/entities/Admin.java, src/main/java/com/tucklets/app/entities/Child.java, src/main/java/com/tucklets/app/services/AdminService.java, src/main/java/com/tucklets/app/services/ChildService.java, src/main/java/com/tucklets/app/services/LoginService.java, src/main/resources/schema.txt, src/main/resources/static/css/login.css, src/main/resources/templates/common-head.html, src/main/resources/templates/header.html, src/main/resources/templates/login.html, src/main/resources/templates/main.html, src/main/resources/templates/sponsor-a-child.html, src/main/resources/templates/sponsor-info.html, src/main/resources/templates/unauthorized.html
- Added basic password hashing with BCrypt.
- Added security module so admin pages are protected.
- Added admin entity + related logic.
=> Added basic login validation

src/main/java/com/tucklets/app/configs/SpringWebSecurityConfig.java, src/main/java/com/tucklets/app/controllers/AdminController.java, src/main/java/com/tucklets/app/controllers/LoginController.java, src/main/java/com/tucklets/app/db/repositories/AdminRepository.java, src/main/java/com/tucklets/app/entities/Admin.java, src/main/java/com/tucklets/app/security/AdminUserDetails.java, src/main/java/com/tucklets/app/security/AdminUserDetailsService.java, src/main/java/com/tucklets/app/services/AdminService.java, src/main/java/com/tucklets/app/services/LoginService.java, src/main/resources/schema.txt, src/main/resources/static/css/dashboard.css, src/main/resources/templates/admin/dashboard.html, src/main/resources/templates/login.html
- Added custom login with security using BCrypt.
- Implemented UserDetailsService + UserDetails to override default behavior.
- Added a basic admin dashboard (needs work)
=> Security updates with a basic admin dashboard

src/main/java/com/tucklets/app/containers/ChildAndSponsorContainer.java, src/main/java/com/tucklets/app/controllers/SponsorInfoController.java, src/main/resources/static/js/sponsor-info.js, src/main/resources/templates/sponsor-info.html
- Added PayPal buttons
- Removed submission button.
=> Added PayPal buttons to the frontend

build.gradle, src/main/java/com/tucklets/app/configs/SpringWebSecurityConfig.java, src/main/java/com/tucklets/app/controllers/AdminController.java, src/main/java/com/tucklets/app/controllers/SponsorChildrenController.java, src/main/java/com/tucklets/app/db/repositories/ChildRepository.java, src/main/java/com/tucklets/app/entities/Admin.java, src/main/java/com/tucklets/app/entities/Child.java, src/main/java/com/tucklets/app/entities/ChildAndSponsorAssoc.java, src/main/java/com/tucklets/app/entities/Sponsor.java, src/main/java/com/tucklets/app/services/ChildService.java, src/main/java/com/tucklets/app/services/PdfService.java, src/main/java/com/tucklets/app/utils/CalculationUtils.java, src/main/java/com/tucklets/app/utils/Constants.java, src/main/java/com/tucklets/app/utils/PdfUtils.java, src/main/resources/schema.txt, src/main/resources/templates/admin/dashboard.html, src/main/resources/templates/header.html
Brought in required dependencies for iText7.
Initial pdfs can now be generation; still needs heavy work.
=> Initial work for PDF generation

.gitignore, build.gradle, package-lock.json, package.json, src/main/java/com/tucklets/app/configs/SpringWebSecurityConfig.java, src/main/java/com/tucklets/app/configs/WebMvcConfig.java, src/main/java/com/tucklets/app/controllers/BasicController.java, src/main/resources/application.properties, src/main/resources/static/jsx/Main.jsx, src/main/resources/templates/home.html, webpack.config.js
Initial commit for setting up webpack with gradle.
Key points:
- Running bootJar or bootRun will call `webpack` task and bundle jsx code.
- `webpack` task will install node/npm so it won't be necessary on dev machine.
=> Set up webpack with gradle

frontend/jsx/Main.jsx, frontend/jsx/shared/LocaleChanger.jsx, src/main/java/com/tucklets/app/configs/SpringWebSecurityConfig.java, src/main/java/com/tucklets/app/controllers/InfoController.java
Refactored Locale to InfoController:
- Renamed LocaleController to InfoController 
- All data info to front end will be written in InfoController
=> Refactored Locale to InfoController

src/main/java/com/tucklets/app/controllers/SponsorInfoController.java, src/main/java/com/tucklets/app/entities/Sponsor.java, src/main/java/com/tucklets/app/entities/enums/SponsorInfoStatus.java, src/main/java/com/tucklets/app/utils/TextUtils.java, src/main/java/com/tucklets/app/validations/DonationValidator.java, src/main/java/com/tucklets/app/validations/SponsorValidator.java
- Backend validations for sponsorInfo page.
- Backend will either throw a 400 or 200 depending on the result of validations.
- Added some logic to lowercase + strip + escape out String inputs from backend (should we make it more difficult on frontend for these things?)
=> Added validations for donation + sponsor

src/main/resources/templates/home.html
Width of website was not changing based on the device size.  I had to add in 
<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
=> Fixed responsiveness on the majority of the pages

frontend/jsx/Main.jsx, frontend/jsx/common/DonationButtonGroup.jsx, frontend/jsx/common/TuckletsNavBar.jsx, frontend/jsx/common/i18n/donate/en_us.json, frontend/jsx/common/i18n/donate/zh_tw.json, frontend/jsx/common/i18n/sponsor-info/en_us.json, frontend/jsx/common/i18n/sponsor-info/zh_tw.json, frontend/jsx/common/utils/donation.js, frontend/jsx/pages/DonatePage.jsx, frontend/jsx/pages/SponsorInfoPage.jsx, frontend/static/scss/_donation-duration.scss, frontend/static/scss/donation.scss, frontend/static/scss/info.scss, frontend/static/scss/sponsor-info.scss, src/main/java/com/tucklets/app/controllers/SponsorInfoController.java, src/main/java/com/tucklets/app/entities/ChildAndSponsorAssoc.java, src/main/java/com/tucklets/app/entities/Donation.java, src/main/java/com/tucklets/app/entities/enums/DonationDuration.java
Created new component (not really reusable) but that component will render the donation buttons appropriately depending on whether we allow duration changes or not.
=> Update UI buttons for donations; force omonthly on sponsor-a-child flow

frontend/jsx/common/i18n.js, frontend/jsx/common/i18n/home/en_us.json, frontend/jsx/common/i18n/home/zh_tw.json, frontend/jsx/pages/HomePage.jsx
i18n made for homepage with Chinese translations as well.
=> Added i18n for home page

frontend/jsx/Main.jsx, frontend/jsx/common/i18n/confirm/en_us.json, frontend/jsx/common/i18n/confirm/zh_tw.json, frontend/jsx/common/sponsorship/ConfirmationTable.jsx, frontend/jsx/common/utils/donation.js, frontend/jsx/pages/ConfirmationPage.jsx, frontend/jsx/pages/NewslettersPage.jsx, frontend/static/scss/confirmation.scss, src/main/java/com/tucklets/app/entities/enums/PaymentMethod.java, src/main/java/com/tucklets/app/services/ManageChildrenService.java, src/main/java/com/tucklets/app/utils/Constants.java, src/main/resources/application-local.properties, src/main/resources/application.properties
Bag of goodies:
- Update confirmation UI by adding check directions
- Propose fix for newsletters issue.
- Add missing-photo to S3
- Add check submission button (fails in backend due to invalid payment method)
- Add basic spring profile for `local`
=> Updated UI for confirmation a bit

deployment/fargate-terraform/service.tf, deployment/fargate-terraform/setup_env.sh, deployment/fargate-terraform/task-definitions/service.json, deployment/fargate-terraform/variables.tf
Removed the environment variable 's3_bucket_name' in terraform
=> Removed terraform variable s3_bucket_name

.circleci/config.yml, build.gradle, deployment/fargate-terraform/iam_roles.tf, deployment/fargate-terraform/service.tf, deployment/fargate-terraform/setup_env.sh, deployment/fargate-terraform/task-definitions/service.json, deployment/fargate-terraform/variables.tf, src/main/resources/application-local.properties, src/main/resources/application.properties, src/main/resources/bootstrap.yml, src/test/java/com/tucklets/app/TuckletsApplicationTests.java
Test is commented out due to Circle CI failure.
Added AWS Secrets Manager integration so secrets in our config can be bootstrapped directly from AWS.
Added test reports as build artifacts.
=> Aws secrets manager integration

deployment/fargate-terraform/modules/service/service.tf, deployment/fargate-terraform/modules/service/variables.tf, deployment/fargate-terraform/setup_env.sh, deployment/fargate-terraform/task-definitions/service.json, deployment/fargate-terraform/variables.tf, src/main/java/com/tucklets/app/configs/AwsConfig.java, src/main/java/com/tucklets/app/configs/SecretsConfig.java, src/main/java/com/tucklets/app/controllers/MainPageController.java
Moved paypal_client_id to secrets manager. This variable is also going to be removed in circle ci's environment variables
=> Moved paypal_client_id to secrets manager

frontend/jsx/Main.jsx, frontend/jsx/common/i18n.js, frontend/jsx/common/i18n/unsubscribe/en_us.json, frontend/jsx/common/i18n/unsubscribe/zh_tw.json, frontend/jsx/common/sponsorship/SponsorForm.jsx, frontend/jsx/pages/SponsorInfoPage.jsx, frontend/jsx/pages/UnsubscribePage.jsx, frontend/static/scss/unsubscribe.scss, src/main/java/com/tucklets/app/configs/AppConfig.java, src/main/java/com/tucklets/app/configs/SpringWebSecurityConfig.java, src/main/java/com/tucklets/app/controllers/SponsorInfoController.java, src/main/java/com/tucklets/app/controllers/UnsubscribeController.java, src/main/java/com/tucklets/app/db/repositories/SponsorRepository.java, src/main/java/com/tucklets/app/services/EmailService.java, src/main/java/com/tucklets/app/services/SponsorService.java, src/main/resources/application-local.properties, src/main/resources/application.properties, src/main/resources/templates/emails/newsletter-email.html
-Added a webpage for unsubscription, linked it to the newsletter email body
=> Unsubscribe from Newsletters Flow

build.gradle, frontend/jsx/Main.jsx, frontend/jsx/common/i18n/donate/en_us.json, frontend/jsx/common/i18n/donate/zh_tw.json, frontend/jsx/common/i18n/sponsor-info/en_us.json, frontend/jsx/common/i18n/sponsor-info/zh_tw.json, frontend/jsx/common/sponsorship/ConfirmationTable.jsx, frontend/jsx/common/sponsorship/DonationForm.jsx, frontend/jsx/common/sponsorship/DonationToggle.jsx, frontend/jsx/common/sponsorship/SponsorForm.jsx, frontend/jsx/common/utils/enums.js, frontend/jsx/pages/ConfirmationPage.jsx, frontend/jsx/pages/DonationInfoPage.jsx, frontend/jsx/pages/SponsorInfoPage.jsx, frontend/static/scss/donation.scss, src/main/java/com/tucklets/app/controllers/InfoController.java, src/main/java/com/tucklets/app/controllers/SponsorInfoController.java, src/main/java/com/tucklets/app/entities/enums/DonationDuration.java, src/main/java/com/tucklets/app/services/DonationService.java, src/main/java/com/tucklets/app/utils/CalculationUtils.java, src/test/java/com/tucklets/app/CalculationUtilsTest.java
- Created a new page to allow users to select the donation duration (monthly, yearly, yearly_recurring).
- When user clicks on a different duration, send a request to the backend to automatically update the amount field.
- Created a unit test to verify the functionality of the new utils method.
=> Donation selection UI

frontend/jsx/common/TuckletsNavBar.jsx, frontend/jsx/common/i18n/locales/en_us.json, frontend/jsx/common/i18n/locales/zh_tw.json
- Reorder tabs in navigation bar.
- "English" language choice will be in English no matter what language preference was selected, Chinese will be in Chinese no matter what as well.
=> Minor UI tweaks

build.gradle, frontend/jsx/pages/ConfirmationPage.jsx, src/main/java/com/tucklets/app/configs/SecretsConfig.java, src/main/java/com/tucklets/app/containers/BrainTreePaymentContainer.java, src/main/java/com/tucklets/app/controllers/SponsorInfoController.java, src/main/java/com/tucklets/app/services/BrainTreePaymentService.java
Created new service class: BrainTreePaymentService.java
- this handles creating brainTree transaction and submitting payment for settling
- Amount is hard coded to 100, will change this after refactor.
=> Process simple transaction to Braintree

src/main/java/com/tucklets/app/configs/AppConfig.java, src/main/java/com/tucklets/app/services/EmailService.java, src/main/resources/application.properties
Minor fixes related to email flow:
- sending email methods are now ASYNCHRONOUS! This means the method will return immediately and that function's logic gets executed in a separate thread. This is nice because after a successful submission, we can return early and show the thank you page. Note: A problem with this approach is that exceptions in the async thread will be harder to catch.
- Add "from" email address so SES will allow us to send emails without passing our machine/device information (seems like default behavior if we do not specify `fromAddress`).
- Update application.properties to only keep relevant email configs.
- Added from address to AppConfig so we can use it for email generation/sending.
=> Minor fixes related to email
